### ISSUE TITLE
macOS Catalina won't let this run

### ISSUE THREAD

**Issue by KyNorthstar** [johnyanarella/MaterialDesignColorPicker#3]
Instead, I get this:
<img width="1137" alt="Screen Shot 2020-09-18 at 08 25 29" src="https://user-images.githubusercontent.com/10189808/93933516-0630f600-fcdf-11ea-93bb-547b4ec652a1.png">

When I press Cancel, this appears, but "Open Anyway" does nothing and has no effect:
<img width="578" alt="Screen Shot 2020-09-22 at 14 23 06" src="https://user-images.githubusercontent.com/10189808/93933623-25c81e80-fcdf-11ea-902d-7cf9dada2531.png">

**Comment by johnyanarella** [comment]
That sounds like even plugins need to be signed / notarized for distribution for Catalina now. Fun. I'll have to look into setting up an appropriate Apple developer account for these purposes.

As a workaround, you should be able to run it on Catalina if you build this from the source code using Xcode locally on your machine.

**Comment by KyNorthstar** [comment]
Yeah, sounds like it. Makes sense if their approach is to use this kind of cryptography to ward off malware; wouldn't want to miss an attack vector.

Just as you say, I ended up compiling it myself lol. Yay for OSS!

Best of luck with signing!

**Comment by KyNorthstar** [comment]
~On my M1 Mac, this is resolved by allowing it in the Security & Privacy preference pane 🎉~

~Seems they did something with M1 that makes this smoother; all my apps with extensions and drivers are easier to approve than on my Intel Mac.~

~Will test tonight on my Intel Mac running Big Sur - hopefully they did something to smooth that too.~

Nevermind. For some reason, macOS decided it shouldn't work anymore 🙄

Seems signing it is the only path forward

**Comment by marcpbailey** [comment]
+1

**Comment by calebtd** [comment]
+1

**Comment by huyz** [comment]
This is still happening on macOS 14.4.1 23E224 (Sonoma).

I did build it myself and it worked, though.

**Comment by xhruso00** [comment]
Correct, it works once I build the project

**Comment by IlIllIl** [comment]
The best way to run unsigned macOS applications or plugins, try `xattr -dr com.apple.quarantine /Users/admin/Library/ColorPickers/MaterialDesignColorPicker.colorPicker`
